version: '2'

services:

    mongodb:
        image: tutum/mongodb
        environment:
            - AUTH=no
        ports:
            - "27017:27017"
            - "28017:28017"
            
    abpidentity_httpapihost:
        image: abpidentity/httpapihost
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging

    abpdesk_web:
        image: abpdesk/web
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging

    load_balancer:
        image: haproxy:1.7.1
        volumes:
            - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
        ports:
            - "9005:8080"